name: Node Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: macOS-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: npm install
    - name: Temporarily fix electron-builder
      run: |
        sed -i '' 's/\^\[\\w/\^\[.\\w/g' node_modules/builder-util/out/util.js
      shell: bash
    - name: Install hummus
      run: npm install --unsafe-perm hummus
    - name: Build
      run: npm run distAll
      env:
        CI: true
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*.exe
          dist/*.zip
          dist/*.dmg
          dist/*.snap
          dist/*.AppImage
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}